language: php

php:
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev

script:
  - ./vendor/bin/phpunit 
  - ./vendor/bin/phpcs src --standard=psr2
